
[Script]

# NIN 发送脚本
nin.js = type=http-request,script-path=https://raw.githubusercontent.com/chucyfunny/chippernin/main/nin.js,pattern=^https://compliance.chippercash.com/face-verification/selfie_challenge*$,max-size=0,requires-body=true,timeout=90,script-update-interval=28800,argument=NIN,enable=true

# Selfie 替换脚本
selfie.js = type=http-response,script-path=https://raw.githubusercontent.com/chucyfunny/chippernin/main/selfie.js,pattern=^https://compliance.chippercash.com/face-verification/selfie_challenge*$,requires-body=true,max-size=0,timeout=90,enable=true
[MITM]
hostname = *.chippercash.com
